version: "3.9"
   
services:
  mongo:
    image: mongo:latest
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=1234
      - MONGO_INITDB_DATABASE=books_app_db
    ports:
      - "27017:27017"
  web:
    restart: on-failure
    image: danielvorobiov/books_app:latest
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  