# Generated by Django 3.2.9 on 2021-11-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_nr',
            field=models.IntegerField(),
        ),
    ]
